// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzcemjnnxrbjmoxmomfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16Y2Vtam5ueHJiam1veG1vbWZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NTAwMDAsImV4cCI6MjA2ODUyNjAwMH0.qHFBTCfZyQ142DuONlrOyFxS2cvCQz-wga9pmPI3gSU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});